#!/usr/bin/env bash
set -euxo pipefail
jupyter nbextension enable --py widgetsnbextension --sys-prefix || true
python - << 'PY'
import numpy, scipy, ipywidgets, matplotlib
print("Binder imports OK")
PY
