name: CI - Fast (unit)

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:

jobs:
  fast:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e . -r requirements.txt
      - name: Unit tests
        run: pytest -q
