name: CI - Integration (toy)

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:

jobs:
  toy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run toy pipeline
        run: |
          python -m flyby.triad --data-root data/toy --out out
          test -f out/triad_summary.csv
          test -f out/triad_report.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toy-out
          path: out/
