name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Air-gapped Formatting Gate
        run: python tools/format_gate.py
      - name: Run tests
        run: pytest -q
      - name: Guardian Safety Gate
        run: python -m simulations.validation.guardian_gates
        if: always()
